### ISSUE TITLE
Incompatible CRD apiextensions.k8s.io/v1beta1 in  EKS with kubernetes 1.22 

### ISSUE THREAD

**Issue by awotch** [coveooss/aws_auth_eks_crd#18]
CRD in v1beta1 

Hello, apiextensions.k8s.io/v1beta1 doesn't work in kubernetes 1.22 , so aws_auth_eks_crd fails to work when we upgrade EKS in version 1.22 the required apiversion is v1. can you update you CRD to work in kubernetes 1.22 ? see the changelog release for kubernetes .

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.22
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

**Comment by JPLachance** [comment]
Good morning!

Can you open a PR? We will review it! We will definitely face the same very soon and your contribution would be really appreciated 😄 

Thanks

**Comment by awotch** [comment]
The new release have been created 0.6.5
